### ISSUE TITLE
New build in 2021

### ISSUE THREAD

**Issue by bortek** [peclik/ogn-airtracker#1]
Hello,

I am planning to build my own OGN tracker and now reading your page which was written about 6 years ago. Some things may have changed since then and I wonder what would be your advice today for building a tracker? Thanks!

**Comment by peclik** [comment]
Hi, more simpler option is to use ready-to-use modules, such as TTGO T-Beam.
See very comprehensive information at https://github.com/lyusupov/SoftRF.

**Comment by bortek** [comment]
Thanks, have already found it. 👍
